// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrVxNB_AcDN83EFJeyVgFeYP-Lnt44o8A',
    appId: '1:656595301587:web:e7224181066febc56d9026',
    messagingSenderId: '656595301587',
    projectId: 'bd-prueba-c9d15',
    authDomain: 'bd-prueba-c9d15.firebaseapp.com',
    storageBucket: 'bd-prueba-c9d15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1-VAtFx1rUgGDf6EZGaL9a-BaQTnNkSs',
    appId: '1:656595301587:android:a4f608e6739e87076d9026',
    messagingSenderId: '656595301587',
    projectId: 'bd-prueba-c9d15',
    storageBucket: 'bd-prueba-c9d15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGGFxBIOhOnWXZ1zdfrxxk-jJhwn6HJsE',
    appId: '1:656595301587:ios:0cda5f46421e5b2d6d9026',
    messagingSenderId: '656595301587',
    projectId: 'bd-prueba-c9d15',
    storageBucket: 'bd-prueba-c9d15.appspot.com',
    iosClientId: '656595301587-pvdovpemc8nsv222o4e4dastg4ei0fn1.apps.googleusercontent.com',
    iosBundleId: 'com.solverticsrl.bdPruebaFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGGFxBIOhOnWXZ1zdfrxxk-jJhwn6HJsE',
    appId: '1:656595301587:ios:34601825658abdd46d9026',
    messagingSenderId: '656595301587',
    projectId: 'bd-prueba-c9d15',
    storageBucket: 'bd-prueba-c9d15.appspot.com',
    iosClientId: '656595301587-6tenuoin4lo8ib4a8tl91uujqtsktrb0.apps.googleusercontent.com',
    iosBundleId: 'com.solverticsrl.bdPruebaFirebase.RunnerTests',
  );
}
